# =============================================================================
#  KKR Gen AI Innovations — Document Scanner AI
#  Word Document Converter
#
#  Saves scanned images + OCR text as a formatted .docx Word file.
#  Requires:  pip install python-docx  Pillow
#
#  Website : https://kkrgenaiinnovations.com/
#  Email   : info@kkrgenaiinnovations.com
#  WhatsApp: +1 470-861-6312
# =============================================================================

from __future__ import annotations

import io
import os
import datetime
import cv2
import numpy as np


class WordConverter:
    """
    Build a styled Microsoft Word (.docx) document from a scanned image
    and optional OCR-extracted text.

    The output document contains:
      - KKR Gen AI Innovations header
      - The scanned document image (embedded, full width)
      - The OCR-extracted text as editable, selectable paragraphs
      - Branded footer with contact info
    """

    BRAND_NAME = "KKR Gen AI Innovations"
    BRAND_URL  = "https://kkrgenaiinnovations.com/"
    BRAND_EMAIL = "info@kkrgenaiinnovations.com"
    BRAND_WA   = "+1 470-861-6312"

    def save(
        self,
        image: np.ndarray,
        output_path: str,
        ocr_text: str = "",
        title: str = "Scanned Document",
        include_image: bool = True,
    ) -> str:
        """
        Build and save the Word document.

        Parameters
        ----------
        image         : scanned image (BGR or grayscale numpy array)
        output_path   : destination path (e.g. "output/scan.docx")
        ocr_text      : OCR-extracted text to embed as editable content
        title         : document title shown as heading
        include_image : embed the scanned image in the document

        Returns
        -------
        str – absolute path to the saved .docx file
        """
        try:
            from docx import Document
            from docx.shared import Inches, Pt, RGBColor, Cm
            from docx.enum.text import WD_ALIGN_PARAGRAPH
            from docx.oxml.ns import qn
            from docx.oxml import OxmlElement
        except ImportError:
            raise ImportError(
                "python-docx is required for Word export.\n"
                "  Fix: pip install python-docx"
            )

        doc = Document()

        # ── Page margins (2 cm all around) ────────────────────────────
        for section in doc.sections:
            section.top_margin    = Cm(2)
            section.bottom_margin = Cm(2)
            section.left_margin   = Cm(2)
            section.right_margin  = Cm(2)

        # ── Header ────────────────────────────────────────────────────
        self._add_header(doc, Pt, RGBColor, WD_ALIGN_PARAGRAPH)

        # ── Document title ─────────────────────────────────────────────
        h = doc.add_heading(title, level=1)
        h.alignment = WD_ALIGN_PARAGRAPH.CENTER
        h.runs[0].font.color.rgb = RGBColor(0x0F, 0x34, 0x60)

        # ── Metadata line ──────────────────────────────────────────────
        meta = doc.add_paragraph()
        meta.alignment = WD_ALIGN_PARAGRAPH.CENTER
        ts   = datetime.datetime.now().strftime("%d %B %Y  %H:%M")
        run  = meta.add_run(f"Generated by Document Scanner AI  |  {ts}")
        run.font.size  = Pt(9)
        run.font.color.rgb = RGBColor(0x71, 0x80, 0x96)
        run.font.italic = True

        doc.add_paragraph()  # spacer

        # ── Scanned image ──────────────────────────────────────────────
        if include_image and image is not None:
            img_para = doc.add_paragraph()
            img_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
            img_bytes = self._image_to_bytes(image)
            run = img_para.add_run()
            run.add_picture(img_bytes, width=Inches(6.0))
            doc.add_paragraph()  # spacer

        # ── OCR text section ───────────────────────────────────────────
        if ocr_text.strip():
            # Section heading
            sh = doc.add_heading("Extracted Text", level=2)
            sh.runs[0].font.color.rgb = RGBColor(0x0F, 0x34, 0x60)

            # Divider
            div = doc.add_paragraph("─" * 60)
            div.runs[0].font.size  = Pt(8)
            div.runs[0].font.color.rgb = RGBColor(0xA0, 0xAE, 0xC0)

            # Each OCR paragraph on its own line
            for line in ocr_text.splitlines():
                p    = doc.add_paragraph()
                run  = p.add_run(line)
                run.font.name = "Courier New"
                run.font.size = Pt(11)
                p.paragraph_format.space_after  = Pt(2)
                p.paragraph_format.space_before = Pt(2)

        else:
            note = doc.add_paragraph()
            note.add_run(
                "[No OCR text available. Run 'Extract Text (OCR)' before saving as Word.]"
            ).font.italic = True

        # ── Footer ────────────────────────────────────────────────────
        self._add_footer(doc, Pt, RGBColor, WD_ALIGN_PARAGRAPH)

        # ── Save ──────────────────────────────────────────────────────
        if not output_path.endswith(".docx"):
            output_path += ".docx"
        os.makedirs(os.path.dirname(os.path.abspath(output_path)), exist_ok=True)
        doc.save(output_path)
        return os.path.abspath(output_path)

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _add_header(self, doc, Pt, RGBColor, WD_ALIGN_PARAGRAPH):
        """Add a branded header to every page."""
        section = doc.sections[0]
        header  = section.header
        para    = header.paragraphs[0] if header.paragraphs else header.add_paragraph()
        para.clear()
        para.alignment = WD_ALIGN_PARAGRAPH.CENTER
        run = para.add_run(
            f"{self.BRAND_NAME}  ·  Document Scanner AI  ·  {self.BRAND_URL}"
        )
        run.font.size  = Pt(8)
        run.font.bold  = True
        run.font.color.rgb = RGBColor(0x0F, 0x34, 0x60)

    def _add_footer(self, doc, Pt, RGBColor, WD_ALIGN_PARAGRAPH):
        """Add a branded footer to every page."""
        section = doc.sections[0]
        footer  = section.footer
        para    = footer.paragraphs[0] if footer.paragraphs else footer.add_paragraph()
        para.clear()
        para.alignment = WD_ALIGN_PARAGRAPH.CENTER
        run = para.add_run(
            f"{self.BRAND_NAME}  |  {self.BRAND_URL}  "
            f"|  {self.BRAND_EMAIL}  |  WhatsApp: {self.BRAND_WA}"
        )
        run.font.size  = Pt(8)
        run.font.color.rgb = RGBColor(0xA0, 0xAE, 0xC0)

    @staticmethod
    def _image_to_bytes(image: np.ndarray) -> io.BytesIO:
        """Encode numpy image → JPEG bytes in a BytesIO buffer."""
        if image.ndim == 2:
            # Grayscale → convert to BGR so JPEG encoder works
            image = cv2.cvtColor(image, cv2.COLOR_GRAY2BGR)
        _, buf    = cv2.imencode(".jpg", image, [cv2.IMWRITE_JPEG_QUALITY, 92])
        return io.BytesIO(buf.tobytes())
